DROP DATABASE IF EXISTS golt;

CREATE DATABASE golt;

USE golt;


CREATE TABLE users (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE codes (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	user_id INTEGER NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE(name, user_id)
);

CREATE TABLE sessions (
	token VARCHAR(100) NOT NULL,
	user_id INTEGER NOT NULL,
	expire_time DATETIME NOT NULL,
	PRIMARY KEY(token),
	FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

